### ISSUE TITLE
[BUG] local에서 회원가입 불가능

### ISSUE THREAD

**Issue by wjdwwidz** [PatientPaI/backend#225]
### 🔄 재현 방법

```bash
1. 로컬 환경에서 서버를 실행한다.
2. register API를 날린다.
3. 터진다.
```

### ✔️ 기대 결과

회원가입이 되어야함.

### ❌ 실제 동작

회원가입이 안 됨. (local 환경 한정)

오류 발생 원인은 db constraint error(not null 컬럼에 null을 insert).
해당 코드는 8월 6일 수정되었고, local에서는 실행시에 h2를 통해서 db-create를 하지만,
prod 환경은 8월 6일 이전에 변경되었기 때문에 해당 설정(not null constraint)가 반영되어 있지 않음.
그래서 정상 동작하고 있습니다.

**Comment by LeeHusung** [comment]
기본 자료형이면 자동으로 not null이 추가되지만 객체형을 사용해서 에러 발생 확인하였습니다.
Integer age -> int age로 수정하면 해결될 것 같습니다.
