### ISSUE TITLE
[BUG] ID, PW로 회원가입시 중복 가입 가능 현상

### ISSUE THREAD

**Issue by wjdwwidz** [PatientPaI/backend#97]
### 🔄 재현 방법

```bash
1. 기존에 존재하는 아이디, 패스워드, 전화번호 입력 후 회원가입
2. 회원가입 성공 (201) 
3. 로그인시 오류 발생 (401)

+) Role 을 다르게 하여도 중복으로 가입되며, 같은 결과를 따릅니다.
```

### ✔️ 기대 결과

사용자 중복 가입은 불가능해야 한다고 간주됩니다.

### ❌ 실제 동작

중복 가입 이후 로그인시 401 Unauthorized 에러 발생 (AU_001)

### 🖥️ 환경 정보

HTTPie

**Comment by su6net** [comment]
@wjdwwidz 아마도 UNIQUE 제약 조건이 걸려있지 않아서 DataIntegrityViolationException이 발생하지 않는 것 같습니다. 자동으로 생성되는 DDL에서 고려될 수 있도록 `@Column`에 unique 속성을 true로 주거나, 향후에 운영 DB에서 수동으로 조정해야 할 것 같습니다 😢
